- name: Desktop Playbook
  hosts: localhost
  roles:
    - role: zsh
      tags:
        zsh
      when: install_zsh
    - role: dotfiles
      tags:
        dotfiles
      when: install_dotfiles
    - role: nvim
      tags:
        nvim
      when: install_nvim
