---
- hosts: localhost
  tags: all
  become: true
  pre_tasks:
    - name: pre-run | Apt update
      tags: always
      apt:
        update_cache: yes
      changed_when: False
      when: ansible_distribution in ["Pop!_OS"]

# roles
- hosts: localhost
  tags: virtual
  become: true
  roles:
    - common
    - virtual
