---
- name: Workstation Initialization Playbook
  hosts: localhost
  pre_tasks:
    - name: pre-run | Apt update
      tags: always
      debug: msg="Running apt"
      changed_when: false
      when: ansible_distribution in ["Pop!_OS"]

- import_playbook: desktop.yml
  tags:
    - desktop
