---
- hosts: all
  tags: all
  become: true
  pre_tasks:
    - name: Pacman - Update cache
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

  #roles
  - hosts: all
    tags: base
    become: true
    roles:
      - base
