---
- hosts: all
  tags: all
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  pre_tasks:
    - name: pre-run | Apt update
      tags: always
      apt:
        update_cache: yes
      changed_when: False
      when: ansible_distribution in ["Pop!_OS"]

# roles
- hosts: virtual
  tags: virtual
  become: true
  roles:
    - common
    - virtual
