- name: install | clone dotfiles
  git:
    repo: https://github.com/fleetscut/dotfiles
    dest: $HOME/.dotfiles

- name: install | Apt install stow
  become: yes
  apt:
    name: stow
    update_cache: yes
