- name: install | Apt Install Zsh
  become: yes
  apt:
    name: zsh
    update_cache: yes

- name: install | get zsh location
  shell: "which zsh"
  register: zsh_path

- name: install | change shell
  become: yes
  user:
    name: "{{ username }}"
    shell: "{{ zsh_path.stdout }}"
  notify: stow zsh configs

- name: install | check oh-my-zsk location
  become_user: "{{ username }}"
  stat:
    path: $HOME/.oh-my-zsh
  register: oh_my_dir

- name: install | download oh-my-zsh
  become_user: "{{ username }}"
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: oh_my_dir.stat.exists == false

- name: install | zsh-autosuggestions
  become_user: "{{ username }}"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: $HOME/.oh-my-zsh/plugins/zsh-autosuggestions
  when: oh_my_dir.stat.exists == false
