---
nvim_reqs:
  - ninja-build
  - gettext
  - libtool
  - libtool-bin
  - autoconf
  - automake
  - cmake
  - g++
  - pkg-config
  - unzip
  - curl
  - doxygen
  - ripgrep
  - fd-find

nvim_pip_reqs:
  - neovim
  - pynvim

nvim_install_path: repos/neovim
nvim_build_type: Release
nvim_repo: https://github.com/neovim/neovim
nvim_branch: master
nvim_bin_path: .local/bin

packer_repo: https://github.com/wbthomason/packer.nvim
packer_dir: $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim

java_lsp_reqs:
  - default-jre
  - default-jdk
  - openjdk-11-doc
  - openjdk-11-source
  - openjdk-17-doc
  - openjdk-17-source
  - npm

eclipse_jdtls_snapshot_url: https://download.eclipse.org/jdtls/snapshots/
#eclipse_jdtls_snapshot_version: jdt-language-server-1.10.0-202203040350.tar.gz
eclipse_jdtls_snapshot_version: jdt-language-server-latest.tar.gz
eclipse_jdtls_download_dir: $HOME/Downloads
eclipse_jdtls_install_dir: $HOME/.local/share/nvim/lsp/jdtls/eclipse.jdt.ls

java_debug_repo: https://github.com/microsoft/java-debug
java_debug_dir: $HOME/.local/share/nvim/lsp/jdtls/java-debug

vscode_java_test_repo: https://github.com/microsoft/vscode-java-test
vscode_java_test_dir: $HOME/.local/share/nvim/lsp/jdtls/vscode-java-test

workspace_dir: $HOME/workspace/

lua_ls_repo: https://github.com/sumneko/lua-language-server
lua_ls_dir: $HOME/.local/share/nvim/lsp/lua/lua-language-server/
lua_ls_compile_dir: /3rd/luamake/

python_reqs:
  - python3-pip

python_ls: jedi_language_server

formatter_reqs:
  - cargo

formatter_lua: stylua
formatter_clang: clang-format
formatter_java: google-java-format
formatter_python: black
formatter_js: prettier

yaml_ls_pip_reqs:
  - ansible-lint

yaml_ls_apt_reqs:
  - yamllint
  - npm

yamlls_npm_reqs: yarn

json_ls_reqs:
  - jsonls

ts_server_reqs:
  - typescript
  - typescript-language-server

cpp_reqs:
  - clangd

rust_analyzer_bin: https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz
rust_install_dir: $HOME/.local/bin/
