---
- name: install pre reqs
  become: yes
  apt:
    name: "{{ formatter_reqs }}"
    update_cache: yes

- name: install stylua
  become_user: "{{ username }}"
  community.general.cargo:
    name: "{{ formatter_lua }}"

- name: install formatters from apt
  become: yes
  apt:
    name:
      - "{{ formatter_clang }}"
      - "{{ formatter_python }}"

- name: install prettier
  become: yes
  npm:
    name: "{{ formatter_js }}"
    global: yes

- name: install google-format-java
  become: yes
  npm:
    name: "{{ formatter_java }}"
    global: yes
