- name: install | download rust analyzer
  become_user: "{{ username }}"
  shell: curl -L https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c > $HOME/.local/bin/rust-analyzer

- name: set executable
  become_user: "{{ username }}"
  shell: chmod +x $HOME/.local/bin/rust-analyzer
