---
- name: install apt pre reqs
  become: yes
  apt:
    name: "{{ yaml_ls_apt_reqs }}"
    update_cache: yes

- name: install pip pre req
  become_user: "{{ username }}"
  pip:
    name: "{{ yaml_ls_pip_reqs }}"
    extra_args: --user

- name: install npm pre req
  become: yes
  npm:
    name: yarn
    global: yes

- name: install yaml-language-server
  become_user: "{{ username }}"
  shell:
    cmd: yarn global add yaml-language-server
